stages:
  - deploy
  - test

deploy_job:
  stage: deploy
  when: always
  image: iterativeai/cml:0-dvc2-base1-gpu
  script:
    - cml-runner --cloud aws --cloud-region us-west --cloud-type g2.2xlarge
      --cloud-spot --labels=cml-runner-gpu

test_runner:
  stage: test
  when: on_success
  tags:
    - cml-runner-gpu
  script:
    - pip install tensorboard

    - npm ci
    - npm run lint
    - npm run test

    - nvidia-smi

test_container:
  stage: test
  when: on_success
  tags:
    - cml-runner-gpu
  image: iterativeai/cml:0-dvc2-base1-gpu
  script:
    - dvc --version
    - pip install tensorboard

    - npm ci
    - npm run lint
    - npm run test

    - nvidia-smi
